version: "3.7"
services:
  api-service:
    build:
      context: ./api/
      dockerfile: Dockerfile
    image: simple-api
    container_name: simple-api-server
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - db-service
    networks:
      - simple-network
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
      DB_CONN: mongodb://db-service:27017/
      DB_NAME: db-simple

  db-service:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - simple-network

  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=MyPassw0rd
      - POSTGRES_USER=sample
    ports:
      - "5432:5432"

networks:
  simple-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
